#!/bin/sh

### Bindings
MOD=Super
# Window Management
riverctl map normal $MOD+Shift Q close
riverctl map normal $MOD+Shift E exit
riverctl map normal $MOD F toggle-fullscreen
riverctl map normal $MOD v toggle-float

# Change Focus
riverctl map normal $MOD J focus-view next
riverctl map normal $MOD K focus-view previous

# Change Location
riverctl map normal $MOD+Shift J swap next
riverctl map normal $MOD+Shift K swap previous
riverctl map normal $MOD Return zoom
riverctl map normal $MOD H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal $MOD L send-layout-cmd rivertile "main-ratio +0.05"

# Change Tags
for i in $(seq 1 10)
do
    tags=$((1 << ($i - 1)))
    button=${i:(-1)}

    # $MOD+[1-9] to focus tag [0-8]
    riverctl map normal $MOD $button set-focused-tags $tags

    # $MOD+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal $MOD+Shift $button set-view-tags $tags

    # $MOD+Ctrl+[1-9] to toggle focus of tag [0-8]
    riverctl map normal $MOD+Control $button toggle-focused-tags $tags

    # $MOD+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal $MOD+Shift+Control $button toggle-view-tags $tags
done
all_tags=$(((1 << 32) - 1))
MOD=Super
riverctl map normal $MOD minus set-focused-tags $all_tags
riverctl map normal $MOD+Shift minus set-view-tags $all_tags

# Change Monitor
riverctl map normal $MOD Period focus-output next
riverctl map normal $MOD Comma focus-output previous
riverctl map normal $MOD+Shift Period send-to-output next
riverctl map normal $MOD+Shift Comma send-to-output previous

# Mouse Stuff
riverctl map-pointer normal $MOD BTN_LEFT move-view
riverctl map-pointer normal $MOD BTN_RIGHT resize-view

# Launchers
riverctl map normal $MOD+Shift Return spawn alacritty
riverctl map normal $MOD d spawn bemenu-run

SCRIPTS=$HOME/.scripts
export DMENU_CMD="bemenu"
riverctl map normal None  XF86AudioRaiseVolume spawn "$SCRIPTS/chVol +5%"
riverctl map normal None  XF86AudioLowerVolume spawn "$SCRIPTS/chVol -5%"
riverctl map normal Shift XF86AudioRaiseVolume spawn "$SCRIPTS/chVol +2%"
riverctl map normal Shift XF86AudioLowerVolume spawn "$SCRIPTS/chVol -2%"
riverctl map normal None  XF86AudioMute        spawn "$SCRIPTS/chVol mute"
riverctl map normal $MOD M                    spawn "$SCRIPTS/chSink"

riverctl map normal None  XF86AudioPlay spawn 'playerctl -p $(cat $HOME/.local/share/mediaPlayer) play-pause'
riverctl map normal None  XF86AudioPrev spawn 'playerctl -p $(cat $HOME/.local/share/mediaPlayer) previous'
riverctl map normal None  XF86AudioNext spawn 'playerctl -p $(cat $HOME/.local/share/mediaPlayer) next'
riverctl map normal $MOD M             spawn "$SCRIPTS/chMp"

riverctl map normal None  XF86MonBrightnessUp   spawn "$SCRIPTS/chBl +10"
riverctl map normal None  XF86MonBrightnessDown spawn "$SCRIPTS/chBl -10"
riverctl map normal Shift XF86MonBrightnessUp   spawn "$SCRIPTS/chBl +5"
riverctl map normal Shift XF86MonBrightnessDown spawn "$SCRIPTS/chBl -5"

### Rules
riverctl float-filter-add app-id pinentry-qt

### Devices
# Outputs
wlr-randr --output eDP-1 --scale 1.5

# Inputs
TOUCHPAD=pointer-1452-640-bcm5974
riverctl input $TOUCHPAD accel-profile adaptive
riverctl input $TOUCHPAD pointer-accel 0.58
riverctl input $TOUCHPAD click-method clickfinger
riverctl input $TOUCHPAD natural-scroll enabled
riverctl input $TOUCHPAD tap disabled

### Settings
# Keyboard Repeat
riverctl set-repeat 50 300
riverctl xcursor-theme macOS-BigSur 26

# Colors
riverctl border-color-focused 0x93a1a1
riverctl border-color-unfocused 0x586e75

# Wallpaper
swaybg -i Downloads/wallhaven-g8d6rd.jpg --mode fill &

### Layout
riverctl attach-mode bottom
riverctl default-layout rivertile
rivertile -view-padding 10
