#!/bin/sh
# Monitor the battery and notify the user if the battery is low

# Variables
charge="$(acpi -b | awk -F'[,:%]' '{ print $3 }')" 
stat="$(acpi -b | awk -F'[,:%]' '{ print $2 }')" 
time="$(acpi -b | awk -F'[,:%]' '{ print $6 }')" 

# Script
if [ $stat = "Discharging" ] && [ $charge -lt 15 ]; then
	dunstify -u critical -r 818 -t 8000 " Battery Level:$charge%" "$time\ minutes remaining"
fi
