#!/bin/bash


echo $PLAYER_EVENT
if [ $PLAYER_EVENT = "start" ] || [ $PLAYER_EVENT = "change" ]; then
	metadata="$(playerctl -p spotifyd metadata)"
	artist="$(echo "$metadata" | grep artist | awk '{$1=$2=""; print substr($0,3)}')"
	title="$(echo "$metadata" | grep title | awk '{$1=$2=""; print substr($0,3)}')"
	
	#dunstify -r 181718 -u low "Playing $title" "by $artist"
	dunstify -r 181718 -u low " Now Playing" "$title - $artist"
fi
