#!/bin/bash

dcmd=${DMENU_CMD:-dmenu}

ID=606606
APP=$(ykman oath accounts list | $dcmd)

dunstify -r $ID "Touch Your Yubikey"

ykman oath accounts code -s "$APP" | xclip -r -selection clipboard

dunstify -r $ID "Copied to clipboard"
